version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Infra!2_25_28_06"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/certs/opensearch.key"
      - "plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/certs/opensearch.key"
      - "plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.allow_default_init_securityindex=true"
    volumes:
      - ./certs:/usr/share/opensearch/config/certs
      - opensearch_data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=false"
      - "OPENSEARCH_USERNAME=admin"
      - "OPENSEARCH_PASSWORD=Infra!2_25_28_06"
      - "OPENSEARCH_SSL_VERIFICATION_MODE=none"
    networks:
      - logging_network
    depends_on:
      - opensearch

networks:
  logging_network:
    driver: bridge

volumes:
  opensearch_data: